### ISSUE TITLE
Not Receiving JWT token after running step 2

### ISSUE THREAD

**Issue by monhustla** [smooch/smooch-python#1]
I run step 2: 

import jwt
token = jwt.encode({scope: app}, 'my secret', algorithm=HS256, headers={kid: 'my key id'})

There is no output. Where do I obtain the JWT following running this?

Thank you

**Comment by alavers** [comment]
The token var should now contain your JWT string, this is what you set for the `smooch.configuration.api_key['Authorization']` in the following step.

I suppose if you just wanted to see the token you could simply to `print token`.
