### ISSUE TITLE
ValueError: Invalid value for `platform` (twilio), must be one of ['ios', 'android', 'web', 'other']

### ISSUE THREAD

**Issue by kolanos** [smooch/smooch-python#2]
This error occurs when `platform` is `twilio`:

      File /"/smooch/models/client.py", line 176, in platform
        .format(platform, allowed_values)
    ValueError: Invalid value for `platform` (twilio), must be one of ['ios', 'android', 'web', 'other']

**Comment by kolanos** [comment]
For clarification this is a result of a `smooch.AppUserAPI().get_app_user(user_id)`.

**Comment by kolanos** [comment]
Current monkey patching workaround:

    from smooch.models.client import Client

    @Client.platform.setter
    def platform(self, platform):
        self._platform = platform

    Client.platform = platform

**Comment by alavers** [comment]
Thanks for filing, I've fixed this in https://github.com/smooch/smooch-python/releases/tag/1.5.0
