### ISSUE TITLE
Messenger integration pageId property not saved on integration

### ISSUE THREAD

**Issue by tjhall13** [smooch/smooch-python#3]
In the smooch docs (https://docs.smooch.io/rest/#list-integrations) the messenger integration object has the pageId returned. This value is not available on the integration object returned by the api.

**Comment by tjhall13** [comment]
The twilio integration is also missing the phoneNumber property

**Comment by Go-Fred** [comment]
Thanks for reporting it! We solved it in https://github.com/smooch/smooch-python/releases/tag/1.8.0
