### ISSUE TITLE
Link app user body params not documented

### ISSUE THREAD

**Issue by tjhall13** [smooch/smooch-python#4]
There exists no way to link a user to a phone number or other entity in the python api. Also, The skip_confirmation is unclear on how it relates to the confirmation object in the http api.

HTTP API: https://docs.smooch.io/rest/#link-app-user-to-channel
Python API: https://github.com/smooch/smooch-python/blob/master/docs/AppUserLink.md

**Comment by jugarrit** [comment]
This is fixed in the most recent release!
